server:
  port: 8081
xxl:
  job:
    accessToken: default_token
    admin:
      addresses: http://127.0.0.1:8888/xxl-job-admin
    executor:
      address: ''
      appname: xxl-job-executor-sample
      ip: ''
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 3
      port: 9999
