spring:
  application:
    # 服务名
    name: tcc-b
  cloud:
    nacos:
      discovery:
        # 服务注册中心
        server-addr: 127.0.0.1:8848
        file-extension: yaml
      loadbalancer:
        ribbon:
          enabled: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bdb?serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=false&characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

# seata 配置
seata:
  enabled: true
  application-id: tcc-b
  config:
    type: nacos
    nacos:
      namespace:
      serverAddr: 127.0.0.1:8848
      group: SEATA_GROUP
      username: "nacos"
      password: "nacos"
      data-id: seataServer.properties
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace:
      username: "nacos"
      password: "nacos"
  tx-service-group: default_tx_group
server:
  # 服务端口
  port: 8082

management:
  # 端点检查（健康检查）
  endpoints:
    web:
      exposure:
        include: "*"
springfox:
  documentation:
    enabled: true